---

- name: clone repo 
  git: repo=https://github.com/absoluteorange/Absolute-Orange-website-code.git dest=/vagrant/www update=no

- name: install application
  make: chdir=/vagrant/www target=install
