---
- hosts: all
  sudo: true
  vars:
    document_root: /vagrant/www/app
  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes
  roles:
    - server
    - ansible-nodejs-role-master
    - aws-cli
    - webserver
    - git
    - mongodb
    - ao
    - database
    - recipes
    - cof-blog
   
