---
- hosts: all
  sudo: true
  vars:
    document_root: /vagrant/www/app
  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes
  roles:
    - ansible-nodejs-role-master
    - server
    - webserver
    - database
    - git
    - mongodb
    - app
   
