---

#Grunt-cli requires a /usr/bin/node directory but the nodejs installation is to /usr/bin/nodejs
- name: Create a symlink from /usr/bin/nodejs to usr/bin/node
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link


- name: Install Grunt CLI
  npm: name=grunt-cli global=yes state=present
  sudo: yes

- name: Install Forever
  npm: name=forever global=yes state=present
  sudo: yes
