---

- name: Install nodejs and some dependencies
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
      - nodejs
      - build-essential
      - npm

#Grunt-cli requires a /usr/bin/node directory but the nodejs installation is to /usr/bin/nodejs
- name: Create a symlink from /usr/bin/nodejs to usr/bin/node
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link

- name: Node.js | Install packages
  npm: global=yes name={{ item }} state=latest
  with_items:
      - grunt
      - grunt-cli
      - grunt-contrib-compass
      - grunt-grunticon-sass
