---

- name: clone repo 
  git: repo=git://github.com/jonreading81/vegan-recipes.git dest=/vagrant/vegan-recipes update=no

- name: install application
  make: chdir=/vagrant/vegan-recipes target=install
