---

- name: Vegan Recipes Service 
  template: src=vegan-recipes.conf.j2 dest=/etc/init/vegan-recipes.conf owner=root group=root mode=0755 backup=no
  notify: restart vegan-recipes
  register: result

- name: Vegan Recipes API Service 
  template: src=vegan-recipes-api.conf.j2 dest=/etc/init/vegan-recipes-api.conf owner=root group=root mode=0755 backup=no
  notify: restart vegan-recipes-api
  register: result

- name: Vegan Recipes API Service 
  template: src=vegan-recipes-api.conf.j2 dest=/etc/init/vegan-recipes-api.conf owner=root group=root mode=0755 backup=no
  notify: restart vegan-recipes-api
  register: result

- name: Adding STORMPATH_CLIENT_APIKEY_ID ENV VAR
  lineinfile: dest=~/.bashrc line='export STORMPATH_CLIENT_APIKEY_ID={{ APIKEY }}' insertafter='EOF' regexp='export STORMPATH_CLIENT_APIKEY_ID={{ APIKEY }}' state=present

- name: Adding export STORMPATH_SECRet VAR
  lineinfile: dest=~/.bashrc line='export STORMPATH_CLIENT_APIKEY_SECRET={{ SECRET }}' insertafter='EOF' regexp='export STORMPATH_CLIENT_APIKEY_SECRET={{ SECRET }}' state=present

- name: Adding export STORMPATH_APPLICATION_HREF VAR
  lineinfile: dest=~/.bashrc line='export STORMPATH_APPLICATION_HREF={{ APPLICATION }}' insertafter='EOF' regexp='export STORMPATH_APPLICATION_HREF={{ APPLICATION }}' state=present

- name: Source .bashrc
  shell: . ~/.bashrc
  become: true

- name: deploy application
  make: chdir=/vagrant/deploy target=deploy-recipes


