---
- name: retrieve deployment 
  get_url: url=https://s3-eu-west-1.amazonaws.com/vegan-recipe-deployments/recipes.tar  dest=/vagrant/recipes.tar


- name: unarchive
  shell: tar -xf /vagrant/recipes.tar -C /vagrant

- name: restore data
  make: chdir=/vagrant/vegan-recipes target=restore-data

- name: build static assets 
  make: chdir=/vagrant/vegan-recipes target=build
