---
- name: retrieve deployment and unarchive
  get_url: url=https://s3-eu-west-1.amazonaws.com/vegan-recipe-deployments/recipes.tar  dest=/vagrant/recipes.tar


- name: restore data application
  shell: tar -xf recipes.tar -C /vagrant/vegan-recipes
    args:
      chdir: /vagrant

- name: restore data application
  make: chdir=/vagrant/vegan-recipes target=restore-data
