---

- name: install mysql
  apt: name={{ item }} state=latest
  with_items:
    - php5-mysql
    - mysql-server
    - python-mysqldb
  notify:
    - reload apache

- name: update mysql root password for all root accounts
  mysql_user: name=amyvarga password=0range host="{{item}}" priv=*.*:ALL,GRANT state=present
  with_items:
  - "{{ ansible_hostname }}"
  - 127.0.0.1
  - ::1
  - localhost

- name: check if DB exists
  shell: mysql -u amyvarga -p0range -h localhost -e 'show databases;' | grep 'amyvarga'
  register: dbstatus
  ignore_errors: True

- name: create database 'amyvarga'
  mysql_db: 
    name=amyvarga 
    state=present
  when: dbstatus.rc != 0

- name: restore SQL file to database 'amyvarga'
  mysql_db: name=amyvarga state=import login_user=amyvarga login_password=0range target=/vagrant/www/database/prod/aol-dev.sql
  when: dbstatus.rc != 0

- name: copy .my.cnf file with root password credentials
  template: 
    src=.my.cnf 
    dest=/home/vagrant/.my.cnf 
    owner=root 
    mode=0600
  when: dbstatus.rc != 0

