---
- name: install mysql
  apt: name={{ item }} state=latest
  with_items:
    - php5-mysql
    - mysql-server
    - python-mysqldb
  notify:
    - reload apache

- name: check if DB 'amyvarga' exists
  shell: mysql -u amyvarga -p 0range -h '%' 'show databases;' | grep 'amyvarga';
  register: dbstatus

- name: create database 'amyvarga'
  mysql_db: 
    name=amyvarga 
    state=present
  when: dbstatus.rc == 0 

- name: 
  mysql_user: 
    name=amyvarga 
    password=0range 
    priv=*.*:ALL,GRANT
    host="%"

- name: update mysql root password for all root accounts
  mysql_user: name=root password=0range host="{{item}}" priv=*.*:ALL,GRANT state=present
  with_items:
  - "{{ ansible_hostname }}"
  - 127.0.0.1
  - ::1
  - localhost

- name: copy .my.cnf file with root password credentials
  template: 
    src=.my.cnf 
    dest=/home/vagrant/.my.cnf 
    owner=root 
    mode=0600

#copy database dump file to remote host and restore it to database 'amyvarga'
- copy: src=amyvarga.sql dest=/tmp
- mysql_db: name=amyvarga state=import login_user=amyvarga login_password=0range target=/tmp/amyvarga.sql

