---
- include: bashAliases.yml

- name: Add vagrant user
  user: name=vagrant

- name: Install zip
  apt: name=zip update_cache=yes state=latest

- name: Install unzip
apt: name=unzip update_cache=yes state=latest
